#define BYTECODE_NOP 0x00
#define BYTECODE_ACONST_NULL 0x01
#define BYTECODE_ICONST_M1 0x02
#define BYTECODE_ICONST_0 0x03
#define BYTECODE_ICONST_1 0x04
#define BYTECODE_ICONST_2 0x05
#define BYTECODE_ICONST_3 0x06
#define BYTECODE_ICONST_4 0x07
#define BYTECODE_ICONST_5 0x08
#define BYTECODE_LCONST_0 0x09
#define BYTECODE_LCONST_1 0x0A
#define BYTECODE_FCONST_0 0x0B
#define BYTECODE_FCONST_1 0x0C
#define BYTECODE_FCONST_2 0x0D
#define BYTECODE_DCONST_0 0x0E
#define BYTECODE_DCONST_1 0x0F
#define BYTECODE_BIPUSH 0x10
#define BYTECODE_SIPUSH 0x11
#define BYTECODE_LDC 0x12
#define BYTECODE_LDC_W 0x13
#define BYTECODE_LDC2_W 0x14
#define BYTECODE_ILOAD 0x15
#define BYTECODE_LLOAD 0x16
#define BYTECODE_FLOAD 0x17
#define BYTECODE_DLOAD 0x18
#define BYTECODE_ALOAD 0x19
#define BYTECODE_ILOAD_0 0x1A
#define BYTECODE_ILOAD_1 0x1B
#define BYTECODE_ILOAD_2 0x1C
#define BYTECODE_ILOAD_3 0x1D
#define BYTECODE_LLOAD_0 0x1E
#define BYTECODE_LLOAD_1 0x1F
#define BYTECODE_LLOAD_2 0x20
#define BYTECODE_LLOAD_3 0x21
#define BYTECODE_FLOAD_0 0x22
#define BYTECODE_FLOAD_1 0x23
#define BYTECODE_FLOAD_2 0x24
#define BYTECODE_FLOAD_3 0x25
#define BYTECODE_DLOAD_0 0x26
#define BYTECODE_DLOAD_1 0x27
#define BYTECODE_DLOAD_2 0x28
#define BYTECODE_DLOAD_3 0x29
#define BYTECODE_ALOAD_0 0x2A
#define BYTECODE_ALOAD_1 0x2B
#define BYTECODE_ALOAD_2 0x2C
#define BYTECODE_ALOAD_3 0x2D
#define BYTECODE_IALOAD 0x2E
#define BYTECODE_LALOAD 0x2F
#define BYTECODE_FALOAD 0x30
#define BYTECODE_DALOAD 0x31
#define BYTECODE_AALOAD 0x32
#define BYTECODE_BALOAD 0x33
#define BYTECODE_CALOAD 0x34
#define BYTECODE_SALOAD 0x35
#define BYTECODE_ISTORE 0x36
#define BYTECODE_LSTORE 0x37
#define BYTECODE_FSTORE 0x38
#define BYTECODE_DSTORE 0x39
#define BYTECODE_ASTORE 0x3A
#define BYTECODE_ISTORE_0 0x3B
#define BYTECODE_ISTORE_1 0x3C
#define BYTECODE_ISTORE_2 0x3D
#define BYTECODE_ISTORE_3 0x3E
#define BYTECODE_LSTORE_0 0x3F
#define BYTECODE_LSTORE_1 0x40
#define BYTECODE_LSTORE_2 0x41
#define BYTECODE_LSTORE_3 0x42
#define BYTECODE_FSTORE_0 0x43
#define BYTECODE_FSTORE_1 0x44
#define BYTECODE_FSTORE_2 0x45
#define BYTECODE_FSTORE_3 0x46
#define BYTECODE_DSTORE_0 0x47
#define BYTECODE_DSTORE_1 0x48
#define BYTECODE_DSTORE_2 0x49
#define BYTECODE_DSTORE_3 0x4A
#define BYTECODE_ASTORE_0 0x4B
#define BYTECODE_ASTORE_1 0x4C
#define BYTECODE_ASTORE_2 0x4D
#define BYTECODE_ASTORE_3 0x4E
#define BYTECODE_IASTORE 0x4F
#define BYTECODE_LASTORE 0x50
#define BYTECODE_FASTORE 0x51
#define BYTECODE_DASTORE 0x52
#define BYTECODE_AASTORE 0x53
#define BYTECODE_BASTORE 0x54
#define BYTECODE_CASTORE 0x55
#define BYTECODE_SASTORE 0x56
#define BYTECODE_POP 0x57
#define BYTECODE_POP2 0x58
#define BYTECODE_DUP 0x59
#define BYTECODE_DUP_X1 0x5A
#define BYTECODE_DUP_X2 0x5B
#define BYTECODE_DUP2 0x5C
#define BYTECODE_DUP2_X1 0x5D
#define BYTECODE_DUP2_X2 0x5E
#define BYTECODE_SWAP 0x5F
#define BYTECODE_IADD 0x60
#define BYTECODE_LADD 0x61
#define BYTECODE_FADD 0x62
#define BYTECODE_DADD 0x63
#define BYTECODE_ISUB 0x64
#define BYTECODE_LSUB 0x65
#define BYTECODE_FSUB 0x66
#define BYTECODE_DSUB 0x67
#define BYTECODE_IMUL 0x68
#define BYTECODE_LMUL 0x69
#define BYTECODE_FMUL 0x6A
#define BYTECODE_DMUL 0x6B
#define BYTECODE_IDIV 0x6C
#define BYTECODE_LDIV 0x6D
#define BYTECODE_FDIV 0x6E
#define BYTECODE_DDIV 0x6F
#define BYTECODE_IREM 0x70
#define BYTECODE_LREM 0x71
#define BYTECODE_FREM 0x72
#define BYTECODE_DREM 0x73
#define BYTECODE_INEG 0x74
#define BYTECODE_LNEG 0x75
#define BYTECODE_FNEG 0x76
#define BYTECODE_DNEG 0x77
#define BYTECODE_ISHL 0x78
#define BYTECODE_LSHL 0x79
#define BYTECODE_ISHR 0x7A
#define BYTECODE_LSHR 0x7B
#define BYTECODE_IUSHR 0x7C
#define BYTECODE_LUSHR 0x7D
#define BYTECODE_IAND 0x7E
#define BYTECODE_LAND 0x7F
#define BYTECODE_IOR 0x80
#define BYTECODE_LOR 0x81
#define BYTECODE_IXOR 0x82
#define BYTECODE_LXOR 0x83
#define BYTECODE_IINC 0x84
#define BYTECODE_I2L 0x85
#define BYTECODE_I2F 0x86
#define BYTECODE_I2D 0x87
#define BYTECODE_L2I 0x88
#define BYTECODE_L2F 0x89
#define BYTECODE_L2D 0x8A
#define BYTECODE_F2I 0x8B
#define BYTECODE_F2L 0x8C
#define BYTECODE_F2D 0x8D
#define BYTECODE_D2I 0x8E
#define BYTECODE_D2L 0x8F
#define BYTECODE_D2F 0x90
#define BYTECODE_I2B 0x91
#define BYTECODE_I2C 0x92
#define BYTECODE_I2S 0x93
#define BYTECODE_LCMP 0x94
#define BYTECODE_FCMPL 0x95
#define BYTECODE_FCMPG 0x96
#define BYTECODE_DCMPL 0x97
#define BYTECODE_DCMPG 0x98
#define BYTECODE_IFEQ 0x99
#define BYTECODE_IFNE 0x9A
#define BYTECODE_IFLT 0x9B
#define BYTECODE_IFGE 0x9C
#define BYTECODE_IFGT 0x9D
#define BYTECODE_IFLE 0x9E
#define BYTECODE_IF_ICMPEQ 0x9F
#define BYTECODE_IF_ICMPNE 0xA0
#define BYTECODE_IF_ICMPLT 0xA1
#define BYTECODE_IF_ICMPGE 0xA2
#define BYTECODE_IF_ICMPGT 0xA3
#define BYTECODE_IF_ICMPLE 0xA4
#define BYTECODE_IF_ACMPEQ 0xA5
#define BYTECODE_IF_ACMPNE 0xA6
#define BYTECODE_GOTO 0xA7
#define BYTECODE_JSR  0xA8
#define BYTECODE_RET  0xA9
#define BYTECODE_TABLESWITCH 0xAA
#define BYTECODE_LOOKUPSWITCH 0xAB
#define BYTECODE_IRETURN 0xAC
#define BYTECODE_LRETURN 0xAD
#define BYTECODE_FRETURN 0xAE
#define BYTECODE_DRETURN 0xAF
#define BYTECODE_ARETURN 0xB0
#define BYTECODE_RETURN 0xB1
#define BYTECODE_GETSTATIC 0xB2
#define BYTECODE_PUTSTATIC 0xB3
#define BYTECODE_GETFIELD 0xB4
#define BYTECODE_PUTFIELD 0xB5
#define BYTECODE_INVOKEVIRTUAL 0xB6
#define BYTECODE_INVOKESPECIAL 0xB7
#define BYTECODE_INVOKESTATIC 0xB8
#define BYTECODE_INVOKEINTERFACE 0xB9
#define BYTECODE_INVOKEDYNAMIC 0xBA
#define BYTECODE_NEW 0xBB
#define BYTECODE_NEWARRAY 0xBC
#define BYTECODE_ANEWARRAY 0xBD
#define BYTECODE_ARRAYLENGTH 0xBE
#define BYTECODE_ATHROW 0xBF
#define BYTECODE_CHECKCAST 0xC0
#define BYTECODE_INSTANCEOF 0xC1
#define BYTECODE_MONITORENTER 0xC2
#define BYTECODE_MONITOREXIT 0xC3
#define BYTECODE_WIDE 0xC4
#define BYTECODE_MULTIANEWARRAY 0xC5
#define BYTECODE_IFNULL 0xC6
#define BYTECODE_IFNONNULL 0xC7
#define BYTECODE_GOTO_W 0xC8
#define BYTECODE_JSR_W 0xC9
#define BYTECODE_BREAKPOINT 0xCA
#define BYTECODE_IMPDEP1 0xFE
#define BYTECODE_IMPDEP2 0xFF










char tabela_nomes_instrucoes[256][15] = {"nop","aconst_null","iconst_m1","iconst_0","iconst_1","iconst_2","iconst_3","iconst_4","iconst_5","lconst_0","lconst_1","fconst_0","fconst_1","fconst_2","dconst_0","dconst_1","bipush","sipush","ldc","ldc_w","ldc2_w","iload","lload","fload","dload","aload","iload_0","iload_1","iload_2","iload_3","lload_0","lload_1","lload_2","lload_3","fload_0","fload_1","fload_2","fload_3","dload_0","dload_1","dload_2","dload_3","aload_0","aload_1","aload_2","aload_3","iaload","laload","faload","daload","aaload","baload","caload","saload","istore","lstore","fstore","dstore","astore","istore_0","istore_1","istore_2","istore_3","lstore_0","lstore_1","lstore_2","lstore_3","fstore_0","fstore_1","fstore_2","fstore_3","dstore_0","dstore_1","dstore_2","dstore_3","astore_0","astore_1","astore_2","astore_3","iastore","lastore","fastore","dastore","aastore","bastore","castore","sastore","pop","pop2","dup","dup_x1","dup_x2","dup2","dup2_x1","dup2_x2","swap","iadd","ladd","fadd","dadd","isub","lsub","fsub","dsub","imul","lmul","fmul","dmul","idiv","ldiv","fdiv","ddiv","irem","lrem","frem","drem","ineg","lneg","fneg","dneg","ishl","lshl","ishr","lshr","iushr","lushr","iand","land","ior","lor","ixor","lxor","iinc","i2l","i2f","i2d","l2i","l2f","l2d","f2i","f2l","f2d","d2i","d2l","d2f","i2b","i2c","i2s","lcmp","fcmpl","fcmpg","dcmpl","dcmpg","ifeq","ifne","iflt","ifge","ifgt","ifle","if_icmpeq","if_icmpne","if_icmplt","if_icmpge","if_icmpgt","if_icmple","if_acmpeq","if_acmpne","goto","jsr ","ret ","tableswitch","lookupswitch","ireturn","lreturn","freturn","dreturn","areturn","return","getstatic","putstatic","getfield","putfield","invokevirtual","invokespecial","invokestatic","invokeinterface","invokedynamic","new","newarray","anewarray","arraylength","athrow","checkcast","instanceof","monitorenter","monitorexit","wide","multianewarray","ifnull","ifnonnull","goto_w","jsr_w","breakpoint","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","not-found","impdep1","impdep2"};


